services:
  postgres:
    image: postgres:18.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-real_time_chat}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  mongodb:
    image: mongo:8.3-noble
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME:-root}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD:-root}
      - MONGODB_INITDB_DATABASE=${MONGODB_INITDB_DATABASE:-real_time_chat}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:8.10-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-root} --appendonly yes
    restart: unless-stopped

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
